/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWeatherRouteImport } from './routes/dashboard.weather'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardThemeRouteImport } from './routes/dashboard.theme'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardSecretsRouteImport } from './routes/dashboard.secrets'
import { Route as DashboardRssRouteImport } from './routes/dashboard.rss'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardPomodoroRouteImport } from './routes/dashboard.pomodoro'
import { Route as DashboardNotesRouteImport } from './routes/dashboard.notes'
import { Route as DashboardNewsRouteImport } from './routes/dashboard.news'
import { Route as DashboardMarketsRouteImport } from './routes/dashboard.markets'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardGithubRouteImport } from './routes/dashboard.github'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardBookmarksRouteImport } from './routes/dashboard.bookmarks'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as ApiThreadsRouteImport } from './routes/api/threads'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiNotesRouteImport } from './routes/api/notes'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiEmailPrefsRouteImport } from './routes/api/email-prefs'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks.$id'
import { Route as ApiNotesIdRouteImport } from './routes/api/notes.$id'
import { Route as ApiEventsIdRouteImport } from './routes/api/events.$id'
import { Route as ApiAiSummarizeNoteRouteImport } from './routes/api/ai.summarize-note'
import { Route as ApiAiSuggestTasksRouteImport } from './routes/api/ai.suggest-tasks'
import { Route as ApiAiBriefingRouteImport } from './routes/api/ai.briefing'
import { Route as ApiThreadsIdMessagesRouteImport } from './routes/api/threads.$id.messages'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWeatherRoute = DashboardWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardThemeRoute = DashboardThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecretsRoute = DashboardSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRssRoute = DashboardRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPomodoroRoute = DashboardPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketsRoute = DashboardMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGithubRoute = DashboardGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookmarksRoute = DashboardBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiThreadsRoute = ApiThreadsRouteImport.update({
  id: '/api/threads',
  path: '/api/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailPrefsRoute = ApiEmailPrefsRouteImport.update({
  id: '/api/email-prefs',
  path: '/api/email-prefs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNotesRoute,
} as any)
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEventsRoute,
} as any)
const ApiAiSummarizeNoteRoute = ApiAiSummarizeNoteRouteImport.update({
  id: '/summarize-note',
  path: '/summarize-note',
  getParentRoute: () => ApiAiRoute,
} as any)
const ApiAiSuggestTasksRoute = ApiAiSuggestTasksRouteImport.update({
  id: '/suggest-tasks',
  path: '/suggest-tasks',
  getParentRoute: () => ApiAiRoute,
} as any)
const ApiAiBriefingRoute = ApiAiBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => ApiAiRoute,
} as any)
const ApiThreadsIdMessagesRoute = ApiThreadsIdMessagesRouteImport.update({
  id: '/$id/messages',
  path: '/$id/messages',
  getParentRoute: () => ApiThreadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ai': typeof ApiAiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/email-prefs': typeof ApiEmailPrefsRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/markets': typeof DashboardMarketsRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/pomodoro': typeof DashboardPomodoroRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rss': typeof DashboardRssRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/theme': typeof DashboardThemeRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/briefing': typeof ApiAiBriefingRoute
  '/api/ai/suggest-tasks': typeof ApiAiSuggestTasksRoute
  '/api/ai/summarize-note': typeof ApiAiSummarizeNoteRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/threads/$id/messages': typeof ApiThreadsIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ai': typeof ApiAiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/email-prefs': typeof ApiEmailPrefsRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/markets': typeof DashboardMarketsRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/pomodoro': typeof DashboardPomodoroRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rss': typeof DashboardRssRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/theme': typeof DashboardThemeRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/ai/briefing': typeof ApiAiBriefingRoute
  '/api/ai/suggest-tasks': typeof ApiAiSuggestTasksRoute
  '/api/ai/summarize-note': typeof ApiAiSummarizeNoteRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/threads/$id/messages': typeof ApiThreadsIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ai': typeof ApiAiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/email-prefs': typeof ApiEmailPrefsRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/projects': typeof ApiProjectsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/threads': typeof ApiThreadsRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/markets': typeof DashboardMarketsRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/pomodoro': typeof DashboardPomodoroRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rss': typeof DashboardRssRoute
  '/dashboard/secrets': typeof DashboardSecretsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/theme': typeof DashboardThemeRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/ai/briefing': typeof ApiAiBriefingRoute
  '/api/ai/suggest-tasks': typeof ApiAiSuggestTasksRoute
  '/api/ai/summarize-note': typeof ApiAiSummarizeNoteRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/threads/$id/messages': typeof ApiThreadsIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/api/ai'
    | '/api/chat'
    | '/api/email-prefs'
    | '/api/events'
    | '/api/notes'
    | '/api/projects'
    | '/api/tasks'
    | '/api/threads'
    | '/dashboard/activity'
    | '/dashboard/bookmarks'
    | '/dashboard/calendar'
    | '/dashboard/chat'
    | '/dashboard/github'
    | '/dashboard/logs'
    | '/dashboard/markets'
    | '/dashboard/news'
    | '/dashboard/notes'
    | '/dashboard/pomodoro'
    | '/dashboard/projects'
    | '/dashboard/rss'
    | '/dashboard/secrets'
    | '/dashboard/tasks'
    | '/dashboard/theme'
    | '/dashboard/users'
    | '/dashboard/weather'
    | '/dashboard/'
    | '/api/ai/briefing'
    | '/api/ai/suggest-tasks'
    | '/api/ai/summarize-note'
    | '/api/events/$id'
    | '/api/notes/$id'
    | '/api/tasks/$id'
    | '/api/threads/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/api/ai'
    | '/api/chat'
    | '/api/email-prefs'
    | '/api/events'
    | '/api/notes'
    | '/api/projects'
    | '/api/tasks'
    | '/api/threads'
    | '/dashboard/activity'
    | '/dashboard/bookmarks'
    | '/dashboard/calendar'
    | '/dashboard/chat'
    | '/dashboard/github'
    | '/dashboard/logs'
    | '/dashboard/markets'
    | '/dashboard/news'
    | '/dashboard/notes'
    | '/dashboard/pomodoro'
    | '/dashboard/projects'
    | '/dashboard/rss'
    | '/dashboard/secrets'
    | '/dashboard/tasks'
    | '/dashboard/theme'
    | '/dashboard/users'
    | '/dashboard/weather'
    | '/dashboard'
    | '/api/ai/briefing'
    | '/api/ai/suggest-tasks'
    | '/api/ai/summarize-note'
    | '/api/events/$id'
    | '/api/notes/$id'
    | '/api/tasks/$id'
    | '/api/threads/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/api/ai'
    | '/api/chat'
    | '/api/email-prefs'
    | '/api/events'
    | '/api/notes'
    | '/api/projects'
    | '/api/tasks'
    | '/api/threads'
    | '/dashboard/activity'
    | '/dashboard/bookmarks'
    | '/dashboard/calendar'
    | '/dashboard/chat'
    | '/dashboard/github'
    | '/dashboard/logs'
    | '/dashboard/markets'
    | '/dashboard/news'
    | '/dashboard/notes'
    | '/dashboard/pomodoro'
    | '/dashboard/projects'
    | '/dashboard/rss'
    | '/dashboard/secrets'
    | '/dashboard/tasks'
    | '/dashboard/theme'
    | '/dashboard/users'
    | '/dashboard/weather'
    | '/dashboard/'
    | '/api/ai/briefing'
    | '/api/ai/suggest-tasks'
    | '/api/ai/summarize-note'
    | '/api/events/$id'
    | '/api/notes/$id'
    | '/api/tasks/$id'
    | '/api/threads/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAiRoute: typeof ApiAiRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiEmailPrefsRoute: typeof ApiEmailPrefsRoute
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiNotesRoute: typeof ApiNotesRouteWithChildren
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
  ApiThreadsRoute: typeof ApiThreadsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/weather': {
      id: '/dashboard/weather'
      path: '/weather'
      fullPath: '/dashboard/weather'
      preLoaderRoute: typeof DashboardWeatherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/theme': {
      id: '/dashboard/theme'
      path: '/theme'
      fullPath: '/dashboard/theme'
      preLoaderRoute: typeof DashboardThemeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/secrets': {
      id: '/dashboard/secrets'
      path: '/secrets'
      fullPath: '/dashboard/secrets'
      preLoaderRoute: typeof DashboardSecretsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rss': {
      id: '/dashboard/rss'
      path: '/rss'
      fullPath: '/dashboard/rss'
      preLoaderRoute: typeof DashboardRssRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pomodoro': {
      id: '/dashboard/pomodoro'
      path: '/pomodoro'
      fullPath: '/dashboard/pomodoro'
      preLoaderRoute: typeof DashboardPomodoroRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/news': {
      id: '/dashboard/news'
      path: '/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/markets': {
      id: '/dashboard/markets'
      path: '/markets'
      fullPath: '/dashboard/markets'
      preLoaderRoute: typeof DashboardMarketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/github': {
      id: '/dashboard/github'
      path: '/github'
      fullPath: '/dashboard/github'
      preLoaderRoute: typeof DashboardGithubRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookmarks': {
      id: '/dashboard/bookmarks'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof DashboardBookmarksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/threads': {
      id: '/api/threads'
      path: '/api/threads'
      fullPath: '/api/threads'
      preLoaderRoute: typeof ApiThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-prefs': {
      id: '/api/email-prefs'
      path: '/api/email-prefs'
      fullPath: '/api/email-prefs'
      preLoaderRoute: typeof ApiEmailPrefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof ApiNotesRoute
    }
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof ApiEventsRoute
    }
    '/api/ai/summarize-note': {
      id: '/api/ai/summarize-note'
      path: '/summarize-note'
      fullPath: '/api/ai/summarize-note'
      preLoaderRoute: typeof ApiAiSummarizeNoteRouteImport
      parentRoute: typeof ApiAiRoute
    }
    '/api/ai/suggest-tasks': {
      id: '/api/ai/suggest-tasks'
      path: '/suggest-tasks'
      fullPath: '/api/ai/suggest-tasks'
      preLoaderRoute: typeof ApiAiSuggestTasksRouteImport
      parentRoute: typeof ApiAiRoute
    }
    '/api/ai/briefing': {
      id: '/api/ai/briefing'
      path: '/briefing'
      fullPath: '/api/ai/briefing'
      preLoaderRoute: typeof ApiAiBriefingRouteImport
      parentRoute: typeof ApiAiRoute
    }
    '/api/threads/$id/messages': {
      id: '/api/threads/$id/messages'
      path: '/$id/messages'
      fullPath: '/api/threads/$id/messages'
      preLoaderRoute: typeof ApiThreadsIdMessagesRouteImport
      parentRoute: typeof ApiThreadsRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardBookmarksRoute: typeof DashboardBookmarksRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardGithubRoute: typeof DashboardGithubRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMarketsRoute: typeof DashboardMarketsRoute
  DashboardNewsRoute: typeof DashboardNewsRoute
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardPomodoroRoute: typeof DashboardPomodoroRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardRssRoute: typeof DashboardRssRoute
  DashboardSecretsRoute: typeof DashboardSecretsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardThemeRoute: typeof DashboardThemeRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWeatherRoute: typeof DashboardWeatherRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardBookmarksRoute: DashboardBookmarksRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardGithubRoute: DashboardGithubRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMarketsRoute: DashboardMarketsRoute,
  DashboardNewsRoute: DashboardNewsRoute,
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardPomodoroRoute: DashboardPomodoroRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardRssRoute: DashboardRssRoute,
  DashboardSecretsRoute: DashboardSecretsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardThemeRoute: DashboardThemeRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWeatherRoute: DashboardWeatherRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiAiRouteChildren {
  ApiAiBriefingRoute: typeof ApiAiBriefingRoute
  ApiAiSuggestTasksRoute: typeof ApiAiSuggestTasksRoute
  ApiAiSummarizeNoteRoute: typeof ApiAiSummarizeNoteRoute
}

const ApiAiRouteChildren: ApiAiRouteChildren = {
  ApiAiBriefingRoute: ApiAiBriefingRoute,
  ApiAiSuggestTasksRoute: ApiAiSuggestTasksRoute,
  ApiAiSummarizeNoteRoute: ApiAiSummarizeNoteRoute,
}

const ApiAiRouteWithChildren = ApiAiRoute._addFileChildren(ApiAiRouteChildren)

interface ApiEventsRouteChildren {
  ApiEventsIdRoute: typeof ApiEventsIdRoute
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsIdRoute: ApiEventsIdRoute,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

interface ApiNotesRouteChildren {
  ApiNotesIdRoute: typeof ApiNotesIdRoute
}

const ApiNotesRouteChildren: ApiNotesRouteChildren = {
  ApiNotesIdRoute: ApiNotesIdRoute,
}

const ApiNotesRouteWithChildren = ApiNotesRoute._addFileChildren(
  ApiNotesRouteChildren,
)

interface ApiTasksRouteChildren {
  ApiTasksIdRoute: typeof ApiTasksIdRoute
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksIdRoute: ApiTasksIdRoute,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

interface ApiThreadsRouteChildren {
  ApiThreadsIdMessagesRoute: typeof ApiThreadsIdMessagesRoute
}

const ApiThreadsRouteChildren: ApiThreadsRouteChildren = {
  ApiThreadsIdMessagesRoute: ApiThreadsIdMessagesRoute,
}

const ApiThreadsRouteWithChildren = ApiThreadsRoute._addFileChildren(
  ApiThreadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAiRoute: ApiAiRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiEmailPrefsRoute: ApiEmailPrefsRoute,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiNotesRoute: ApiNotesRouteWithChildren,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiTasksRoute: ApiTasksRouteWithChildren,
  ApiThreadsRoute: ApiThreadsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
